### ISSUE TITLE
Error 500 Server Error

### ISSUE THREAD

**Issue by 1v-0** [lucasdavid/wikiart#10]
````
git clone https://github.com/lucasdavid/wikiart.git
python3 wikiart.py --verbose
````

=> 

info: Fetching artists... Error 500 Server Error: Internal Server Error for url: https://www.wikiart.org/en/App/Home/Error/5bddbfbfedc2c909b4eaf823

**Comment by bfod** [comment]
I'm also seeing this

**Comment by AnBucquet** [comment]
Same for me. I think it's because the Url of wikiart for the fetching has changed.
'https://www.wikiart.org/en/App/Painting/' doesn't exist anymore and so the ImageJson.

**Comment by lucasdavid** [comment]
Sorry for taking so long to answer this. I keep forgetting after coming from work...

@AnBucquet that would be very awkward from their part. Link changes usually result in 300 answers instead of 500 (we are crashing their service with our requests).
I'll try to look more into this in the evening.

**Comment by lucasdavid** [comment]
So I sent emails and used the contact section in their website a week ago, and no one replied.
It's a shame but I think we'll have to archive this repository. Sorry guys. :-(

**Comment by lucasdavid** [comment]
Okay! They answered me with the new API docs. Would someone like to patch this? (-:

**Comment by akshai9899** [comment]
Hey I would like to do this. 

And I don't know much about this so I'd be happy if I get a little help too :)

**Comment by lucasdavid** [comment]
Awesome!
It doesn't look much different, except it needs to request for an auth token beforehand.
Let me know anything how things go/what I can do to help. (-:
The link for the docs:
https://docs.google.com/document/d/1T926unU7mx9Blmx3c8UE0UQTnO3MrDbXTGYVerVQFDU

**Comment by akshai9899** [comment]
Hey,
I added the authentication but after tinkering around I found out that it is not required. 
So I am sending a PR with the way around and the function for obtaining SessionKey, maybe that will help out in future

**Comment by lucasdavid** [comment]
Thank you for your help!
