### ISSUE TITLE
Download artwork by search term?

### ISSUE THREAD

**Issue by pseudomonas** [lucasdavid/wikiart#11]
I have a [URL](https://www.wikiart.org/en/paintingadvancedsearch#!#filter:advanced,minYear:0,maxYear:1700,dictionaries:57726bcdedc2cb3880ae73be) for an advanced search; is there any way that either I can feed this to the downloader, replicate its functionality within the downloader, or get wikiart to spit out a JSON file representing the artworks encompassed?

**Comment by lucasdavid** [comment]
It seems the api is no longer working (used by the downloader). I sent them a message questioning this, but it's not clear how the downloader will keep working now (even when downloading everything and not only your advanced search). Let me fix that first and I circle back to answer you.

**Comment by lucasdavid** [comment]
The [docs](https://docs.google.com/document/d/1T926unU7mx9Blmx3c8UE0UQTnO3MrDbXTGYVerVQFDU/edit#heading=h.8poty0o44bam) state we can search paintings by requesting to `/PaintingSearch` using a `searchTerm` parameter. This code doesn't currently do this, but it might be possible to do what you want by using the string after `filter:` in your advanced search URL as a search term.
Would you like to try it?
