### ISSUE TITLE
Technique/material empty

### ISSUE THREAD

**Issue by tomazderca** [lucasdavid/wikiart#15]
If you happen to still be here, I hope you might be able to help me. 

It seems wikiart might how changed their classification for paintings works from technique/material to just media.  However, using your fetcher I still have the old notation, and the fields technique and material remain empty (default to null). Now, I've looked at the code, but I can't really find a way as to how I would change the requests in a way where that would get fixed.

I'd be more than happy if you have any idea how to fix this.
Thank you very much.

**Comment by lucasdavid** [comment]
I'm focusing on other things right now and I probably not going to have time to fix this :(
However, I managed to analyze what needs to be changed so you receive the new meta information! Currently, this is being performed:

1. A list of painters are retrieved from `https://www.wikiart.org/en/App/Artist/AlphabetJson`
2. For each artist described by an `url`:
    2.1. Retrieve a list of paintings from `https://www.wikiart.org/en/App/Painting/PaintingsByArtist?artistUrl={url}`
    2.2. For each painting retrieved, fetch the detailed painting info from `https://www.wikiart.org/en/App/Painting/ImageJson/{contentId}`

This needs to be changed into:

1. Retrieve the list of artists from `https://www.wikiart.org/en/api/2/UpdatedArtists` until the parameter `hasMore` is `False`
2. For each artist represented by an `id`:
    2.1. Retrieve the list of paintings from `https://www.wikiart.org/en/api/2/PaintingsByArtist?id={id}`
    2.2. For each painting retrieved, fetch its details at `https://www.wikiart.org/en/api/2/Painting?id={painting_id}`

This should be enough. Hope it helps.

You can find the [v2 docs here](https://docs.google.com/document/d/1T926unU7mx9Blmx3c8UE0UQTnO3MrDbXTGYVerVQFDU).

**Comment by lucasdavid** [comment]
Fixed in the [apiv2 branch](https://github.com/lucasdavid/wikiart/tree/apiv2).
