### ISSUE TITLE
Connection aborted.

### ISSUE THREAD

**Issue by AnnTap** [lucasdavid/wikiart#16]
I got the error `'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer') ` for almost every Painter. I just want to mention it in case someone else is struggling with that, because I fixed it.

I changed some values in .wikiart/settings.py:

```
REQUEST_STRIDE = 9
REQUEST_PADDING_IN_SECS = 5
METADATA_REQUEST_TIMEOUT = 20 * 60
PAINTINGS_REQUEST_TIMEOUT = 20 * 60
```
That helped.

**Comment by lucasdavid** [comment]
Thanks for the hint. This is usually related with slower internet connections, which require a long time to download the largest files. I'm glad you managed to solve it by increasing timeout!
