### ISSUE TITLE
The images in folder

### ISSUE THREAD

**Issue by diaodeyi** [lucasdavid/wikiart#18]
I use the script by almost half a day, but the images folder still empty , how long does it take for download metadata?

**Comment by lucasdavid** [comment]
Is the meta folder growing? If the console is not frozen, then things is fine. In any case, it does take a long time indeed. The workflow is like this:
```
1. Retrieves the the artists index, which is pretty quick
2. For every artist A
   a. retrieve the list of paintings of A
   b. for every painting P of artist A
      i. retrieve metadata associated with P
   c. consolidate all information into the file `meta/{A}.json`
```

Calls for metadata are sequential, but I think the code could be easily changed to make them parallel. We just need to make sure it does not violate the maximum number of calls allowed by the server in the determined time window... Contributions are always welcomed. :-)

**Comment by lucasdavid** [comment]
If the download has been interrupted for any reason, you can just run the script again. It will scan the existing files and start from where it left it.
