### ISSUE TITLE
KeyError when fetching

### ISSUE THREAD

**Issue by shinyben** [lucasdavid/wikiart#19]
Running `python wikiart.py --datadir ./wikiart-saved/ fetch` I get the following after `queen-marie-antoinette-on-the-way-to-her-execution-1793 (s)`:

Windows 11 x64, Python 3.8.0

```
File "wikiart.py", line 4, in <module>
    main()
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\console.py", line 104, in main
    Console().interpret()
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\console.py", line 68, in interpret
    args.func(args)
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\console.py", line 83, in fetch
    f.fetch_all()
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\fetcher.py", line 94, in fetch_all
    return (self.fetch_artists()
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\fetcher.py", line 216, in copy_everything
    self.download_hard_copy(painting)
  File "H:\Home\Images\Autogenerated\Wikiart\wikiart-master\wikiart\fetcher.py", line 233, in download_hard_copy
    painting['artistUrl'],
KeyError: 'artistUrl'
```

**Comment by lucasdavid** [comment]
That's odd. The file might be corrupted? Try to remove the artist's metadata .json and run it again. Let me know if this works it.

**Comment by shinyben** [comment]
The JSON entry looks like this (has no `artistUrl`). This could be from my network cutting out at random times, which happened during the process.

Removing the entry allows the script to move past that particular KeyError.

```
    {
        "title": "The Death of Marat",
        "contentId": 197943,
        "artistContentId": 196187,
        "artistName": "Jacques-Louis David",
        "completitionYear": 1793,
        "yearAsString": "1793",
        "width": 800,
        "image": "https://uploads6.wikiart.org/00381/images/jacques-louis-david/800px-death-of-marat-by-david.jpg!Large.jpg",
        "height": 1029
    },
```

**Comment by lucasdavid** [comment]
Hmmm. Connection issues are unlikely to corrupt the file, because it's being transmitted through TCP.
I think it's more probable that the code itself has corrupted the file or this entry is simply invalid (wikiart has a new API which doesn't have artistUrl as attribute, so I'm not entirely sure they are keeping track of problems in this one).

In fact, I have the code (made by a friend) that pulls data from the new API (contains more information like material, and painting properties). I've been unable to test it myself, but I could upload it to a secondary branch in this repository.
Would you have some time to help me by testing it out?
Should be just like this one + insert a usage key.

**Comment by lucasdavid** [comment]
In any case, I added it to the branch apiv2.

**Comment by shinyben** [comment]
What would you like me to do to test?

**Comment by lucasdavid** [comment]
Just download the paintings using it and let me know if you get any errors! :)
But no promises or rush, do it whenever you can.
If you are unable to do it, then it's fine too, just please let me know.

**Comment by shinyben** [comment]
Sure, I should be able to get around to it. Could you send me the script & command?

**Comment by lucasdavid** [comment]
I added it to the apiv2 branch in here: https://github.com/lucasdavid/wikiart/tree/apiv2
You can just move to the branch and run the code normally:
```
git fetch --all
git checkout apiv2
python wikiart.py ... 
```
