### ISSUE TITLE
Download all art for a given artist

### ISSUE THREAD

**Issue by multimeric** [lucasdavid/wikiart#2]
Is your tool able to do this? There seem to be relevant functions in the API, it just doesn't seem like it from the CLI help.

**Comment by lucasdavid** [comment]
There's no clean way to do it, maybe you would like to submit a pull request? :-)

And yet, a hacky way to do it would be to:

1. download the artists metadata and let this application generate a `artists.json` for you using the `python __main__.py --only artists`
2. open `artists.json` and remove all artists that do not interest you
3. execute this code again with `python __main__.py --only paintings`

**Comment by lucasdavid** [comment]
I'm closing this. Let me know if it didn't help you.

**Comment by trimcao** [comment]
What does it mean to run `python __main__.py`? I'm sorry that I do not know python enough :)

**Comment by multimeric** [comment]
He updated the file named `__main__.py` to `wikiart.py`

**Comment by lucasdavid** [comment]
Yeah, `wikiart.py` is the new entry-point for the code. You just need to run it:
```shell
$ python wikiart.py --datadir /path/to/output/
```

**Comment by trimcao** [comment]
So what is the command for `python __main__.py --only paintings` now?
I would like to try downloading a few artists' paintings on wikiart.

**Comment by lucasdavid** [comment]
It works exactly like before, but replacing `__main__` with `wikiart`:  
download the `artists.json` file with `python wikiart.py --only artists --override`, remove all entries except by the artists you want to fetch and run `python wikiart.py --only paintings`.
