### ISSUE TITLE
new to coding and python

### ISSUE THREAD

**Issue by kotddl** [lucasdavid/wikiart#23]
Hello,
I'm trying to figure out how to install or run this file. I want to get into python more but I can't figure it out so if you could let me know how to do this on a Mac I'd really appreciate it. 

thanks.

**Comment by lucasdavid** [comment]
Hello. You need to download and install python from here: https://www.python.org/
Then you need to copy this code to your PC. You can do so by clicking on the green button in the upper right corner that says "clone repository". Then navigate to the folder and run `pip install requests` to install this dependency and, finally, run the code with `python wikiart.py`.

**Comment by kotddl** [comment]
Hello, I've been navigating to that folder in terminal, even after installing python and I enter `pip install requests` but it returns with the error "no such directory or file"

What should I do?

**Comment by kotddl** [comment]
So I have managed to get it to work by downloading PyPI, but now where do I use the command to download only one specific artist? When I run wikiart.py it automatically starts downloading every single artist

**Comment by lucasdavid** [comment]
You need to specify which author you want to download. The parameter --only can be used for that:
```py
python wikiart.py --only gogh
```
It accepts the name or part of the name of an artist.

**Comment by kotddl** [comment]
Hi thanks again. So Im typing in `python3 wikiart.py --only zdzislaw-beksinski ` but it returns with wikiart.py: error: argument {fetch,convert}: invalid choice: 'zdzislaw beksinski' (choose from 'fetch', 'convert')

**Comment by lucasdavid** [comment]
Ok. Something must have changed in the last pr. Try python3 wikiart.py fetch --only beksinski (add the word fetch between .py and --only).

**Comment by lucasdavid** [comment]
@kotddl are you still having trouble? Let me know if the above has worked for you.
