### ISSUE TITLE
Title of artwork as filename?

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [lucasdavid/wikiart#25]
The downloaded filenames are just numbers. How do I make the files be named after the artwork's title instead?

**Comment by lucasdavid** [comment]
The metadata json file created will have both filename and title info, as well as many other fields. You can read this file in a python program or Excel and inspect each name.

If you want the files to be named after their titles, you have to replace `str(painting['contentId'])` by `str(painting['title'])` in [line #254 in wikiart/fetcher.py](https://github.com/lucasdavid/wikiart/blob/25118b7997c11062531e59805f39c65fa2391775/wikiart/fetcher.py#L254) file.

It should be like this:

```py
def download_hard_copy(self, painting):
    ...
    filename = os.path.join(settings.BASE_FOLDER,
                            'images',
                            painting['artistUrl'],
                            str(painting['completitionYear']) if painting['completitionYear'] else 'unknown-year',
                            str(painting['title']) +  # Add `title` instead of `contentId` here.
                            settings.SAVE_IMAGES_IN_FORMAT)
```
