### ISSUE TITLE
Error in Mac with Python3 homebrew installation

### ISSUE THREAD

**Issue by LETRA** [lucasdavid/wikiart#3]
Hello. I'am not very experienced user of macOS console. The commands give me a error:

```
Mac-mini-de-:~ xxxxxxx$ python3 /Users/xxxx/Desktop/wikiart-master/setup.py install
Traceback (most recent call last):
  File "/Users/xxxxx/Desktop/wikiart-master/setup.py", line 22, in <module>
    long_description=open('README.md').read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md' 
```

And:

```
Mac-mini-de:~ xxxxxx$ python3 /Applications/wikiart-master/__main__.py --help
Traceback (most recent call last):
  File "/Applications/wikiart-master/__main__.py", line 1, in <module>
    from wikiart.console import main
  File "/Applications/wikiart-master/wikiart/console.py", line 11, in <module>
    from . import base, converter, fetcher, settings
  File "/Applications/wikiart-master/wikiart/fetcher.py", line 14, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
I search in google but no find solution.

Any help?

**Comment by lucasdavid** [comment]
1. It seems the `README.md` file is missing. Did you clone the project entirely (with the clone/download buttons), or just downloaded parts of it?
In case you did clone the project, then just comment the line `long_description=open('README.md').read(),` before running the `setup.py` script.

2. You are missing a dependency (requests). `python setup.py install/develop` should install those for you. You can also do it manually: `pip install requests --upgrade`

**Comment by lucasdavid** [comment]
It occurred to me that the first problem might also be happening because you didn't navigated to the project's folder before installing it. In other words:
DO NOT do this: `python /projects/wikiart/setup.py install`
DO this:
```
cd /projects/wikiart
python setup.py install
```

**Comment by LETRA** [comment]
Thank you. Works perfectly.
