### ISSUE TITLE
can you share us the wikiart data you downloaded?

### ISSUE THREAD

**Issue by zgxiangyang** [lucasdavid/wikiart#4]
It's too slow to download from api.

**Comment by lucasdavid** [comment]
Sorry buddy. I don't have servers to support this load. Also, this would have huge legal implications (e.g. content being removed) which I most definitely don't have time to deal with.

You could try to improve speed by increasing `REQUEST_STRIDE` and reducing `REQUEST_PADDING_IN_SECS` in the `settings.py` file.
