### ISSUE TITLE
Cannot download the images

### ISSUE THREAD

**Issue by trimcao** [lucasdavid/wikiart#5]
Hi Lucas,
I have run your script but I did not find any downloaded images in the /images folder although getting the metadata is fine. I'm using python 3.6. 
Thanks.

**Comment by lucasdavid** [comment]
Did you finished downloading the metadata? The download of paintings' files only start afterwards.

If yes: it's hard for me to say what's going on with that little information.
Please post here your platform, package versions (you can find this with `pip freeze`), the output of the script and an overview of what was downloaded.

**Comment by lucasdavid** [comment]
Did you finished downloading the metadata? The download of paintings' files only start afterwards.

**Comment by trimcao** [comment]
Thanks, I did not know download of paintings come later.
