### ISSUE TITLE
Module not found error: no module named 'requests'

### ISSUE THREAD

**Issue by Kamikaze-88** [lucasdavid/wikiart#7]
Installed python 3.6.5
and ran the following through command prompt as admin:

python wikiart.py --datadir ./wikiart-saved/ fetch --only artists

I get an error:

 File "wikiart.py", line 1, in <module>
    from wikiart.console import main
  File "G:\[Software 2]\WikiArt Downloader\wikiart-master\wikiart\console.py", line 11, in <module>
    from . import base, converter, fetcher, settings
  File "G:\[Software 2]\WikiArt Downloader\wikiart-master\wikiart\fetcher.py", line 14, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by lucasdavid** [comment]
You need requests. Run `pip install requests` before anything else. Installing this package will also download and install requests for you.

**Comment by Kamikaze-88** [comment]
Thanks that did the trick!

Thanks a lot for this tool Lucas, it helps a lot :)
