### ISSUE TITLE
Downloading paintings from a specific artist.

### ISSUE THREAD

**Issue by modar-k** [lucasdavid/wikiart#9]
Hello.
I'm trying to download the paintings from a single artist, I removed all the the other artists from the .json file, but still, when I run the `wikiart.py --datadir /datasets/wikiart/ fetch` command, the paintings from all the artists on wikiart are being fetched.

**Comment by lucasdavid** [comment]
Show me the content in your meta json file.

**Comment by modar-k** [comment]
```
[
    {
        "contentId": 195896,
        "artistName": "Ivan Aivazovsky",
        "url": "ivan-aivazovsky",
        "lastNameFirst": "Aivazovsky Ivan ",
        "birthDay": "/Date(-4810154400000)/",
        "deathDay": "/Date(-61998660000000)/",
        "birthDayAsString": "29 July 1817",
        "deathDayAsString": "05 May 1900",
        "image": "https://uploads3.wikiart.org/images/ivan-aivazovsky.jpg!Portrait.jpg",
        "wikipediaUrl": "http://en.wikipedia.org/wiki/Ivan_Aivazovsky",
        "dictonaries": [
            310,
            2738,
            1505,
            2297
        ]
    }
]
```

**Comment by lucasdavid** [comment]
Are you sure that's the only file in your `meta` folder? I'll check once I get back from work, but this should work out as it is...

**Comment by modar-k** [comment]
**UPDATE:** I got it fixed. It turned out that the the `wikiart.py --datadir /datasets/wikiart/ fetch` command  reads the  artists.json file located in `/datasets/wikiart/meta/` not in `./wikiart-saved/meta/artists.json` and therfore it's the one that should be edited.

**Comment by modar-k** [comment]
**UPDATE:** I got it fixed. It turned out that the the `wikiart.py --datadir /datasets/wikiart/ fetch` command  reads the  artists.json file located in `/datasets/wikiart/meta/` and not the one located in `./wikiart-saved/meta/` therefore it's the former that needs to be edited. It's working perfectly now, thank you.

**Comment by lucasdavid** [comment]
This looks like a bug. Thank you for reporting. Maybe you could also submit a PR?

**Comment by modar-k** [comment]
I'm really sorry Lucas, but I didn't make any changes to the code, and I have no experience in Python. All I did was to manually replace the `artists.json` file in `datasets/wikiart/meta` with the one in` ./wikiart-saved/meta` (the one I edited) and then running the `wikiart.py --datadir /datasets/wikiart/ fetch `command again.

**Comment by lucasdavid** [comment]
No problem. Glad it worked out.
